import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    areaview:{
        flex: 1,
        backgroundColor: '#000',
    },
    container: {
        flex: 1,
        backgroundColor: '#00001f',
        alignItems: 'center',
        justifyContent: 'center',
    },
    mamac: {
        width: '100%',
        position: 'absolute',
        borderTopRightRadius: 35,
        borderTopLeftRadius: 35,
        alignItems:'center',
        top: '13%',
    },
    contain: {
        backgroundColor: 'green',
        width: '100%',
        height: '60%',
        position: 'absolute',
        borderTopRightRadius: 35,
        borderTopLeftRadius: 35,
        bottom: 0,
    },
    textvalue: {
        width: '90%',
        height: 80,
        fontSize:30,
        marginTop: 20,
        color:'white',
    },
    displayvalue: {
        width: '90%',
        height: 80,
        fontWeight:'700',
        marginTop: 10,
        fontSize:60,
        color:'white',
        textAlign:"right",
    },
    blackbox: {
        backgroundColor: '#002030',
        width: '75%',
        height: '80%',
        position: 'absolute',
        bottom: 0,
        flexDirection: 'row',
        left: 0,
    },
    topbox: {
        backgroundColor: 'black',
        width: '75%',
        height: '20%',
        position: 'absolute',
        top: 0,
        left: 0,
        borderTopLeftRadius: 35,
        flexDirection: 'row',
        justifyContent: 'space-evenly'
    },
    viewbox: {
        backgroundColor: '#000031',
        width: '25%',
        height: '100%',
        position: 'absolute',
        bottom: 0,
        right: 0,
        borderTopRightRadius: 35,
    },
    equalb: {
        backgroundColor: '#ffbf00',
        width: '100%',
        height: '40%',
        position: 'absolute',
        bottom: 0,
        alignItems: 'center',
        justifyContent: 'center'
    },
    equalt: {
        fontSize: 75,
        fontWeight: '600',
        color: '#fff',
    },
    equalrt: {
        fontSize: 55,
        fontWeight: '300',
        color: 'yellow',
    },
    equalrot: {
        fontSize: 45,
        fontWeight: '700',
        color: 'white',
    },
    equalr: {
        backgroundColor: '#020353',
        width: '100%',
        height: '20%',
        alignItems: 'center',
        justifyContent: 'center',
        borderColor: 'black',
        borderWidth: 1,
    },
    equall: {
        backgroundColor: '#020353',
        width: '33%',
        height: '100%',
        alignItems: 'center',
        justifyContent: 'center',
        borderColor: 'black',
        borderWidth: 1,
    },
    equallol: {
        backgroundColor: '#020353',
        width: '33%',
        height: '100%',
        alignItems: 'center',
        justifyContent: 'center',
        borderColor: 'black',
        borderWidth: 1,
        borderTopLeftRadius: 35,
    },
    equallot: {
        backgroundColor: '#020353',
        width: '100%',
        height: '20%',
        alignItems: 'center',
        justifyContent: 'center',
        borderColor: 'black',
        borderWidth: 1,
        borderTopRightRadius: 35,
    },
    top: {
        backgroundColor: '#020353',
        width: '33%',
        height: '100%',
        borderColor: 'black',
        borderWidth: 1,
    },
    tried: {
        backgroundColor: '#212121',
        width: '100%',
        height: '25%',
        alignItems: 'center',
        justifyContent: 'center',
        borderColor: 'black',
        borderWidth: 1,
    },
    equaltried: {
        fontSize: 35,
        fontWeight: '400',
        color: 'white',
    },
});
